### ISSUE TITLE
maybe use WeakMaps for private data, instead of underscore-prefix?

### ISSUE THREAD

**Issue by jokeyrhyme** [R1ZZU/events2#3]
http://ilikekillnerds.com/2015/09/privates-in-es2015-javascript-classes/

**Comment by R1ZZU** [comment]
is the game worth the candle? This approach could decrease the readability and simplicity of solution...

**Comment by jokeyrhyme** [comment]
I may have misunderstood the purpose of this project.

In any case, I think being able to use the word "private" throughout the code makes the intent clearer than just an underscore-prefix. And it certainly makes it more tamper-proof.

**Comment by R1ZZU** [comment]
underscore-as-"this is private"-indicator is very common in js world, so `private` in property name is redundant

**Comment by jokeyrhyme** [comment]
This is _your_ project, so ultimately these decisions are yours and yours alone.

I'm just pointing out that underscore-prefixes don't actually make data safe and private, they just fake it. ES2015 WeakMaps are the best solution we have so far for instance-private data, and it'd be a shame to continue abusing underscores in this way.

**Comment by R1ZZU** [comment]
WeakMaps are just fine, but let's wait for some legit way of making private props 😉 (! mean ES7 annotations)
